context:
  version: "5.8.0"

package:
  name: certbot-dns-route53
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/certbot-dns-route53/certbot_dns_route53-${{ version }}.tar.gz
  sha256: de2d294074f7a0c084c708fdc6217474e8196917b0c4f98929fa9de78076e9b6

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - acme >=${{ version }}
    - certbot >=${{ version }}
    - boto3 >=1.20.34

tests:
  - python:
      imports:
        - certbot_dns_route53
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  homepage: https://certbot.eff.org
  summary: Amazon Web Services Route 53 DNS Authenticator plugin for Certbot
  license: Apache-2.0
  license_file: LICENSE.txt
  documentation: https://certbot.eff.org
  repository: https://github.com/certbot/certbot

extra:
  recipe-maintainers:
    - pavelzw
